# configs/loss/interpretable.yaml
_target_: babysteerling.loss.CompositeLoss

losses:
  token:
    - _target_: babysteerling.loss.TokenLoss
    - 1.0
  concept:
    - _target_: babysteerling.loss.ConceptLoss
    - 1.0
  steering:
    - _target_: babysteerling.loss.ExpressLoss
    - 1.0

metrics:
  token_accuracy:
    _target_: babysteerling.metric.TokenAccuracy
  concept_auc:
    _target_: babysteerling.metric.ConceptAUC
  causal_concept_effect:
    _target_: babysteerling.metric.CausalConceptEffect
