# configs/loss/standard.yaml
_target_: babysteerling.loss.CompositeLoss

losses:
  token:
    - _target_: babysteerling.loss.DiffusionTokenLoss
    - 1.0

metrics:
  token_accuracy:
    _target_: babysteerling.metric.TokenAccuracy